# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Период работы с')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Период работы по')),
                ('workplace', models.CharField(blank=True, default='', max_length=100, verbose_name='Место работы')),
                ('responsibility', models.TextField(blank=True, default='', verbose_name='Обязанности')),
                ('salary', models.IntegerField(blank=True, default=0, verbose_name='Зарплата')),
                ('reason_leaving', models.TextField(blank=True, default='', verbose_name='Причина увольнения')),
            ],
            options={
                'verbose_name_plural': 'Опыт работы',
                'verbose_name': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_date', models.DateField(auto_now_add=True)),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('full_name', models.CharField(max_length=100, verbose_name='Фамилия, имя, отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sex', models.IntegerField(blank=True, choices=[(0, 'Мужской'), (1, 'Женский'), (2, 'Не указан')], default=2, verbose_name='Пол')),
                ('registration', models.TextField(blank=True, default='', verbose_name='Адрес прописки')),
                ('residence', models.BooleanField(default=True, verbose_name='Адрес проживания')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='Мобильный телефон')),
                ('children', models.BooleanField(default=False, verbose_name='Дети')),
                ('passp_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Серия, номер паспорта')),
                ('passp_issue', models.CharField(blank=True, default='', max_length=50, verbose_name='Кем выдан')),
                ('passp_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('army', models.BooleanField(default=False, verbose_name='Служба в армии')),
                ('army_id', models.BooleanField(default=False, verbose_name='Военный билет')),
                ('driver_lic', models.BooleanField(default=False, verbose_name='Водительское удостоверение')),
                ('car', models.BooleanField(default=False, verbose_name='Личный автомобиль')),
                ('advantage', models.TextField(blank=True, default='', verbose_name='Ваши сильные стороны')),
                ('disadvantage', models.TextField(blank=True, default='', verbose_name='Ваши слабые стороны')),
                ('convicted', models.BooleanField(default=False, verbose_name='Привлекались ли Вы к ответственности (административной, уголовной и т.д.)')),
                ('illness', models.BooleanField(default=False, verbose_name='Страдаете ли Вы хроническими заболеваниями?')),
                ('salary', models.IntegerField(blank=True, default=0, verbose_name='Какую заработную плату Вы хотите получать?')),
            ],
            options={
                'verbose_name_plural': 'Соискатели',
                'verbose_name': 'Соискатель',
            },
        ),
        migrations.CreateModel(
            name='Residence_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.TextField(blank=True, default='', verbose_name='Адрес проживания')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Person')),
            ],
            options={
                'verbose_name_plural': 'Адрес проживания',
                'verbose_name': 'Адрес проживания',
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Person'),
        ),
    ]
