# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание обучения')),
                ('name_institute', models.TextField(blank=True, default='', verbose_name='Название учебного заведения, факультет, форма обучения')),
                ('qualification', models.CharField(blank=True, default='', max_length=50, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Образование и специальность',
                'verbose_name_plural': 'Образование и специальность',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_start_date', models.DateField(blank=True, null=True, verbose_name='Период работы с')),
                ('exp_end_date', models.DateField(blank=True, null=True, verbose_name='Период работы по')),
                ('workplace', models.CharField(blank=True, default='', max_length=100, verbose_name='Место работы')),
                ('exp_position', models.CharField(blank=True, default='', max_length=100, verbose_name='Должность')),
                ('responsibility', models.TextField(blank=True, default='', max_length=100, verbose_name='Обязанности')),
                ('exp_salary', models.CharField(blank=True, default='', max_length=10, verbose_name='Зарплата')),
                ('reason_leaving', models.TextField(blank=True, default='', max_length=100, verbose_name='Причина увольнения')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_date', models.DateField(auto_now_add=True, verbose_name='Дата заполнения')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('full_name', models.CharField(max_length=100, verbose_name='Фамилия, имя, отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('0', 'Мужской'), ('1', 'Женский')], default='', max_length=1, verbose_name='Пол')),
                ('registration', models.TextField(blank=True, default='', verbose_name='Адрес прописки')),
                ('residenceBool', models.BooleanField(default=True, verbose_name='Адрес проживания совпадает с адресом прописки')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='Мобильный телефон')),
                ('civil_status', models.CharField(blank=True, choices=[('Не женат', 'Не женат'), ('Не замужем', 'Не замужем'), ('Женат', 'Женат'), ('Замужем', 'Замужем'), ('Розведен(а)', 'Розведен(а)')], default='', max_length=10, verbose_name='Семейное положение')),
                ('children', models.BooleanField(default=False, verbose_name='Дети')),
                ('quant_children', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default='0', verbose_name='Количество детей')),
                ('passp_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Серия, номер паспорта')),
                ('passp_issue', models.CharField(blank=True, default='', max_length=50, verbose_name='Кем выдан')),
                ('passp_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('army', models.BooleanField(default=False, verbose_name='Служба в армии')),
                ('army_id', models.BooleanField(default=False, verbose_name='Военный билет')),
                ('driver_lic', models.BooleanField(default=False, verbose_name='Водительское удостоверение')),
                ('car', models.BooleanField(default=False, verbose_name='Личный автомобиль')),
                ('advantage', models.TextField(blank=True, default='', verbose_name='Ваши сильные стороны')),
                ('disadvantage', models.TextField(blank=True, default='', verbose_name='Ваши слабые стороны')),
                ('convicted', models.BooleanField(default=False, verbose_name='Привлекались ли Вы к ответственности (административной, уголовной и т.д.)')),
                ('illness', models.BooleanField(default=False, verbose_name='Страдаете ли Вы хроническими заболеваниями?')),
                ('salary', models.CharField(blank=True, default='', max_length=10, verbose_name='Какую заработную плату Вы хотите получать?')),
                ('ref1_full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия, имя, отчество')),
                ('ref1_position', models.CharField(blank=True, default='', max_length=50, verbose_name='Должность')),
                ('ref1_workplace', models.CharField(blank=True, default='', max_length=100, verbose_name='Место работы')),
                ('ref1_phone', models.CharField(blank=True, default='', max_length=15, verbose_name='Мобильный телефон')),
                ('ref2_full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия, имя, отчество')),
                ('ref2_position', models.CharField(blank=True, default='', max_length=50, verbose_name='Должность')),
                ('ref2_workplace', models.CharField(blank=True, default='', max_length=100, verbose_name='Место работы')),
                ('ref2_phone', models.CharField(blank=True, default='', max_length=15, verbose_name='Мобильный телефон')),
                ('source_about_as', models.CharField(blank=True, default='', max_length=50, verbose_name='Из какого источника узнали о вакансии')),
                ('add_details', models.TextField(blank=True, default='', verbose_name='Дополнительне данные')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Могу начать работать')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.CreateModel(
            name='Residence_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.TextField(blank=True, default='', verbose_name='Адрес проживания')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Person')),
            ],
            options={
                'verbose_name': 'Адрес проживания',
                'verbose_name_plural': 'Адрес проживания',
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Person'),
        ),
        migrations.AddField(
            model_name='education',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Person'),
        ),
    ]
