# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='reason_leaving',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Причина увольнения'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibility',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Мужской'), (1, 'Женский')], default=2, verbose_name='Пол'),
        ),
    ]
