# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fill_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заполнения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence',
            field=models.BooleanField(default=True, verbose_name='Адрес проживания совпадает с адресом прописки'),
        ),
    ]
