# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20170611_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[(0, 'Мужской'), (1, 'Женский')], default=2, max_length=10, verbose_name='Пол'),
        ),
    ]
