# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20170618_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Женат/Замужем', 'Женат/Замужем'), ('Не женат/Не замужем', 'Не женат/Не замужем')], default='', max_length=20, verbose_name='Семейное положение'),
        ),
    ]
