# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20170624_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='children',
        ),
        migrations.AlterField(
            model_name='person',
            name='add_details',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительные сведения, которые Вы желаете сообщить о себе'),
        ),
        migrations.AlterField(
            model_name='person',
            name='quant_children',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default='0', verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='person',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Когда Вы можете начать работать'),
        ),
    ]
