# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20170625_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailToAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Фамилия, имя, отчество')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
            ],
        ),
        migrations.CreateModel(
            name='MailToGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(verbose_name='Номер группы')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Описание группы')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='mail_to_group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер группы получателей почты'),
        ),
        migrations.AddField(
            model_name='mailtoaddress',
            name='mail_to_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.MailToGroup'),
        ),
    ]
