# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20170713_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtoaddress',
            options={'verbose_name': 'Электронная почта: адресат', 'verbose_name_plural': 'Электронная почта: адресаты'},
        ),
        migrations.AlterModelOptions(
            name='mailtogroup',
            options={'verbose_name': 'Электронная почта: группы получателей', 'verbose_name_plural': 'Электронная почта: группы получателей'},
        ),
        migrations.AddField(
            model_name='person',
            name='email_send',
            field=models.BooleanField(default=False, editable=False, verbose_name='Анкета отправлена почтой'),
        ),
        migrations.AlterField(
            model_name='mailtoaddress',
            name='mail_to_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.MailToGroup', verbose_name='Группа получателей'),
        ),
        migrations.AlterField(
            model_name='mailtogroup',
            name='group_number',
            field=models.IntegerField(unique=True, verbose_name='Номер группы'),
        ),
    ]
