# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20170721_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBackSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='Использовать TLS')),
                ('email_host', models.CharField(default='smtp.product.in.ua', max_length=50, verbose_name='EMAIL_HOST (сервер)')),
                ('email_host_user', models.EmailField(default='job@product.in.ua', max_length=50, verbose_name='EMAIL_HOST_USER')),
                ('email_host_password', models.CharField(default='A126YzSd6Kjm9At', max_length=50, verbose_name='EMAIL_HOST_PASSWORD')),
                ('email_port', models.IntegerField(default=587, verbose_name='EMAIL_PORT')),
            ],
            options={
                'verbose_name_plural': 'Backend настройки отправки почты',
                'verbose_name': 'Backend настройки отправки почты',
            },
        ),
    ]
