# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_mailbacksettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbacksettings',
            options={'verbose_name': 'Настройки отправки почты', 'verbose_name_plural': 'Настройки отправки почты'},
        ),
    ]
