# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_auto_20170723_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtogroup',
            name='mail_back_settings',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='candidate.MailBackSettings', verbose_name='Настройки отправки почты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailtoaddress',
            name='mail_to_group',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.MailToGroup', verbose_name='Группа получателей'),
        ),
    ]
