# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_auto_20170725_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbacksettings',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Описание настроек отправки почты'),
        ),
    ]
