# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-22 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0014_mailbacksettings_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_group', models.ManyToManyField(to='candidate.MailToAddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адресаты пользователя',
                'verbose_name_plural': 'Адресаты пользователя',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='quant_children',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0, verbose_name='Количество детей'),
        ),
    ]
