# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_auto_20171129_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='mail_to',
            field=models.ManyToManyField(related_name='locations', to='candidate.MailToAddress', verbose_name='Получатели почты'),
        ),
    ]
