# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_auto_20171129_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fill_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.Location', verbose_name='Место заполнения'),
        ),
    ]
