# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 17:20
from __future__ import unicode_literals

from django.db import migrations

def add_cv_status(apps, schema_editor):
    Person = apps.get_model("candidate", "Person")
    CvStatus = apps.get_model("cv_manager", "CvStatusName")
    CvState = apps.get_model("cv_manager", "CvState")

    cv_status_5 = CvStatus.objects.get(status=5)

    for person in Person.objects.all():
        cv_state = CvState(cv=person, status=cv_status_5)
        cv_state.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cv_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_cv_status),
    ]
