# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0018_auto_20171129_1409'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VcState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(default='', max_length=200, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Статусы анкет',
                'verbose_name_plural': 'Статусы анкет',
            },
        ),
        migrations.CreateModel(
            name='VcStatusName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Новое'), (1, 'Просмотренное'), (2, 'Собеседование'), (3, 'Принят'), (4, 'НЕ принят'), (5, 'Архив')], verbose_name='Статус резюме')),
            ],
            options={
                'verbose_name': 'Справочник: Статусы анкеты',
                'verbose_name_plural': 'Справочник: Статусы анкеты',
            },
        ),
        migrations.AddField(
            model_name='vcstate',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vc_manager.VcStatusName', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='vcstate',
            name='user_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='getter', to=settings.AUTH_USER_MODEL, verbose_name='Кому назначено'),
        ),
        migrations.AddField(
            model_name='vcstate',
            name='user_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setter', to=settings.AUTH_USER_MODEL, verbose_name='Установил статус'),
        ),
        migrations.AddField(
            model_name='vcstate',
            name='vc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Person', verbose_name='ID Person'),
        ),
    ]
