# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vc_manager', '0002_auto_20180220_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcstate',
            options={'get_latest_by': 'date', 'verbose_name': 'Статусы анкет', 'verbose_name_plural': 'Статусы анкет'},
        ),
        migrations.AlterField(
            model_name='vcstate',
            name='user_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='getter', to=settings.AUTH_USER_MODEL, verbose_name='Кому назначено'),
        ),
        migrations.AlterField(
            model_name='vcstate',
            name='user_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setter', to=settings.AUTH_USER_MODEL, verbose_name='Установил статус'),
        ),
    ]
